name: Go Copyright Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-copyright:
    name: Ensure Go Files Have Copyright Notice
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Go file copyrights
        run: |
          ERROR=0
          COPYRIGHT_LINE="// Copyright © 2025 Ping Identity Corporation"
          
          # Find all Go files
          for file in $(find . -type f -name "*.go"); do
            # Read the first few lines of the file
            if ! head -n 5 "$file" | grep -q "$COPYRIGHT_LINE"; then
              echo "❌ Missing copyright in: $file"
              ERROR=1
            fi
          done

          if [[ $ERROR -ne 0 ]]; then
            echo "🚨 Some Go files are missing the copyright notice. Please fix them."
            exit 1
          else
            echo "✅ All Go files contain the required copyright notice."
          fi
